spring:
  #thymeleaf 설정
  thymeleaf:
    check-template-location: true
    prefix: classpath:/tmeplates/ #.html 파일 경로 (src/main/resources/templates)
    suffix: .html #확장자
    cache: false # default: true, 개발 시에는 false로 두는 것이 좋음 // true를 해주면 새로고침 해도 반영 안됌.
  mvc:
    static-path-pattern: /static/** # spring mvc 정적 파일들의 경로(css, js파일 등)
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0:3306/spring_db # spring_db 부분은 설정한 DB명과 맞춘다.
    username: root
    password:
mybatis:
  mapper-locations:
    - classpath:mappers/*.xml
    - configuration:
        map-underscore-to-camel-case: true # (DB)value_name ->(Java)valueName 자동 매핑

server:
  servlet:
    context-path: /
  port: 8081 # 웹 서버의 포트 번호
